# LMO mission heartbeat (constitution section 11) -- orchestrator-armed auto-resume.
#
# The 5-hour usage window (and crashes, reboots, power loss) must not kill a mission. The
# orchestrator ARMS a per-run scheduled task as soon as .mission/<run-id>/ exists, and DISARMS
# it at DELIVER. Each BEAT is idempotent:
#   active run            -> exit (something touched the run dir or transcript recently)
#   interrupted marker    -> headless resume from committed state (claude -p --resume)
#   complete/absent marker-> self-disarm + exit
#
#   arm:     powershell -NoProfile -ExecutionPolicy Bypass -File mission_heartbeat.ps1 arm    -RunDir <repo>\.mission\<run-id>
#   beat:    (scheduled task only)                          mission_heartbeat.ps1 beat   -Lock <run-dir>\mission.lock
#   disarm:  powershell -NoProfile -ExecutionPolicy Bypass -File mission_heartbeat.ps1 disarm -RunDir <repo>\.mission\<run-id>
#   status:  powershell -NoProfile -ExecutionPolicy Bypass -File mission_heartbeat.ps1 status -RunDir <repo>\.mission\<run-id>
#
# Headless resume runs under the DEFAULT permission mode -- pre-granting broader autonomy
# (e.g. the Workflow tool) is a human settings action, never this script's.
param(
    [Parameter(Mandatory = $true, Position = 0)][ValidateSet('arm', 'beat', 'disarm', 'status')]
    [string]$Action,
    [string]$RunDir,
    [string]$Lock,
    [int]$IntervalMin = 30,   # beat cadence
    [int]$StaleMin = 45,      # no activity for this long => the run is presumed dead
    [int]$MaxResumes = 3,     # §11 backstop: total resume attempts before the beat gives up + disarms
    [switch]$DryRun           # beat: log the resume decision but do not launch claude
)
$ErrorActionPreference = 'Stop'
$LogFile = Join-Path $env:USERPROFILE '.claude\heartbeat.log'
$ScriptsDir = Join-Path $env:USERPROFILE '.claude\scripts'

function Log([string]$msg) {
    $line = "{0:yyyy-MM-dd HH:mm:ss}  {1}" -f (Get-Date), $msg
    Write-Host $line
    Add-Content -Path $LogFile -Value $line
}

# Claude Code encodes a path into a projects/ dir name by replacing every non-alphanumeric
# char with '-'. Worktree sessions write their transcript under the MAIN repo's project dir.
function Encode-ProjectDir([string]$path) { return ($path -replace '[^A-Za-z0-9]', '-') }

function Resolve-Roots([string]$runDir) {
    # <repo-root>\.mission\<run-id> -> repo root (may be a worktree) + main repo root
    $repoRoot = Split-Path -Parent (Split-Path -Parent $runDir)
    $mainRoot = $repoRoot
    $ix = $repoRoot.IndexOf('\.claude\worktrees\')
    if ($ix -gt 0) { $mainRoot = $repoRoot.Substring(0, $ix) }
    return @($repoRoot, $mainRoot)
}

function Find-Transcripts($cfg) {
    # Newest-first session transcripts that belong to this repo (or its worktrees) and
    # mention the run id. The prefix filter keeps sibling repos (natalie_share) and
    # unrelated sessions that merely discuss the run out of the candidate set.
    $projects = Join-Path $env:USERPROFILE '.claude\projects'
    Get-ChildItem $projects -Directory |
        Where-Object { $_.Name -eq $cfg.project_prefix -or $_.Name -like ($cfg.project_prefix + '--*') } |
        ForEach-Object { Get-ChildItem $_.FullName -Filter '*.jsonl' -File -ErrorAction SilentlyContinue } |
        Where-Object { $_.LastWriteTime -gt (Get-Date).AddDays(-14) } |
        Where-Object { Select-String -Path $_.FullName -Pattern $cfg.run_id -Quiet -ErrorAction SilentlyContinue } |
        Sort-Object LastWriteTime -Descending
}

switch ($Action) {

    'arm' {
        if (-not $RunDir) { throw 'arm requires -RunDir' }
        $RunDir = (Resolve-Path $RunDir).Path
        $runId = Split-Path -Leaf $RunDir
        $roots = Resolve-Roots $RunDir
        $taskName = "LMO\Heartbeat-$runId"
        $lockPath = Join-Path $RunDir 'mission.lock'

        $cfg = [ordered]@{
            run_id         = $runId
            run_dir        = $RunDir
            cwd            = $roots[1]                     # main repo root: where transcripts + resume live
            project_prefix = Encode-ProjectDir $roots[1]
            task           = $taskName
            interval_min   = $IntervalMin
            stale_min      = $StaleMin
            armed_at       = (Get-Date -Format 'o')
        }
        $cfg | ConvertTo-Json | Set-Content -Path $lockPath -Encoding UTF8

        # Fresh start: clear any resume ledger / dead marker left by a prior arming of this run,
        # so a deliberate re-arm (e.g. after the human resolves the usage window) is not instantly
        # disarmed by a spent budget from last time.
        Remove-Item (Join-Path $RunDir 'heartbeat.resumes.json'), (Join-Path $RunDir 'heartbeat.dead') -ErrorAction SilentlyContinue

        # Per-run beat wrapper (hard-coded lock path) so run_hidden.vbs needs no arg plumbing.
        $cmdPath = Join-Path $ScriptsDir "heartbeat-$runId.cmd"
        @"
@echo off
REM Auto-generated by mission_heartbeat.ps1 arm -- beat wrapper for run $runId.
cd /d "%USERPROFILE%\.claude\scripts"
powershell -NoProfile -ExecutionPolicy Bypass -File mission_heartbeat.ps1 beat -Lock "$lockPath" >> "%USERPROFILE%\.claude\heartbeat.log" 2>&1
"@ | Set-Content -Path $cmdPath -Encoding ASCII

        $vbs = Join-Path $ScriptsDir 'run_hidden.vbs'
        if (-not (Test-Path $vbs)) { throw "run_hidden.vbs not deployed -- run scripts\deploy.ps1 first" }
        try { schtasks /Delete /F /TN $taskName 2>$null | Out-Null } catch { }
        schtasks /Create /F /TN $taskName /TR "wscript.exe `"$vbs`" heartbeat-$runId.cmd" /SC MINUTE /MO $IntervalMin | Out-Null
        Log "ARM   $runId  task=$taskName every ${IntervalMin}min  stale>${StaleMin}min  lock=$lockPath"
    }

    'beat' {
        if (-not $Lock) { throw 'beat requires -Lock' }
        $runDirFromLock = Split-Path -Parent $Lock
        $runId = Split-Path -Leaf $runDirFromLock
        $taskName = "LMO\Heartbeat-$runId"

        # Absent marker -> disarm + exit (mission ended and cleaned up, or run dir gone).
        if (-not (Test-Path $Lock)) {
            Log "BEAT  $runId  lock absent -> self-disarm"
            try { schtasks /Delete /F /TN $taskName 2>$null | Out-Null } catch { }
            Remove-Item (Join-Path $ScriptsDir "heartbeat-$runId.cmd") -ErrorAction SilentlyContinue
            exit 0
        }
        $cfg = Get-Content $Lock -Raw | ConvertFrom-Json

        # Complete marker -> disarm + exit (DELIVER leaves REPORT.md; disarm belongs to DELIVER
        # but the beat self-disarms as a backstop).
        if (Test-Path (Join-Path $cfg.run_dir 'REPORT.md')) {
            Log "BEAT  $runId  REPORT.md present -> mission delivered -> self-disarm"
            try { schtasks /Delete /F /TN $taskName 2>$null | Out-Null } catch { }
            Remove-Item (Join-Path $ScriptsDir "heartbeat-$runId.cmd") -ErrorAction SilentlyContinue
            Remove-Item $Lock -ErrorAction SilentlyContinue
            exit 0
        }

        # Activity check: newest touch across the run dir and this repo's mission transcripts.
        # EXCLUDE the heartbeat's own bookkeeping -- counting our own writes as "activity" would
        # let a beat mistake its own footprint for mission progress and resume forever.
        $bookkeeping = @('mission.lock', 'heartbeat.spawning', 'heartbeat.resumes.json', 'heartbeat.dead')
        $transcripts = @(Find-Transcripts $cfg)
        $newest = (Get-Item $Lock).LastWriteTime
        Get-ChildItem $cfg.run_dir -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $bookkeeping -notcontains $_.Name } |
            ForEach-Object { if ($_.LastWriteTime -gt $newest) { $newest = $_.LastWriteTime } }
        if ($transcripts.Count -gt 0 -and $transcripts[0].LastWriteTime -gt $newest) { $newest = $transcripts[0].LastWriteTime }
        $idleMin = [int]((Get-Date) - $newest).TotalMinutes
        if ($idleMin -lt $cfg.stale_min) {
            Log "BEAT  $runId  active (last touch ${idleMin}min ago < $($cfg.stale_min)) -> exit"
            exit 0
        }

        # §11 invariant -- "a stale heartbeat survives at most one firing." A resume that produced
        # NO new mission activity is a DEAD resume; re-firing it every interval just burns the usage
        # window (observed: 23 firings on natalie-fable-revision-20260609, staleness 59->599 min,
        # zero progress, ~400K cold tokens per beat). So before resuming again: if the previous
        # resume failed to advance $newest, or the total resume budget is spent, DISARM and leave a
        # heartbeat.dead marker for the morning report -- a dead-and-unrecoverable run is a §12 alarm,
        # not something to retry into the ground.
        $ledgerPath = Join-Path $cfg.run_dir 'heartbeat.resumes.json'
        $ledger = if (Test-Path $ledgerPath) { Get-Content $ledgerPath -Raw | ConvertFrom-Json }
                  else { [pscustomobject]@{ attempts = 0; resumed_from = '' } }
        $attempts = [int]$ledger.attempts
        $deadReason = $null
        if ($attempts -ge $MaxResumes) {
            $deadReason = "resume budget exhausted ($attempts/$MaxResumes attempts)"
        }
        elseif ($attempts -ge 1 -and $ledger.resumed_from -and ([datetime]$ledger.resumed_from -ge $newest)) {
            $deadReason = "prior resume made no progress (stale ${idleMin}min, no advance since attempt $attempts)"
        }
        if ($deadReason) {
            $deadMsg = "Mission $runId presumed dead and unrecoverable by heartbeat: $deadReason. " +
                "A human must inspect the run dir ($($cfg.run_dir)) and resume or close it."
            if (-not $DryRun) { Set-Content -Path (Join-Path $cfg.run_dir 'heartbeat.dead') -Value $deadMsg -Encoding UTF8 }
            Log "BEAT  $runId  $deadReason -> self-disarm + escalate (heartbeat.dead)$(if ($DryRun) {' [DRY-RUN]'})"
            if (-not $DryRun) {
                try { schtasks /Delete /F /TN $taskName 2>$null | Out-Null } catch { }
                Remove-Item (Join-Path $ScriptsDir "heartbeat-$runId.cmd") -ErrorAction SilentlyContinue
            }
            exit 0
        }

        # Spawn guard: one resume in flight at a time (a resumed mission can run for hours).
        $spawnLock = Join-Path $cfg.run_dir 'heartbeat.spawning'
        if ((Test-Path $spawnLock) -and ((Get-Date) - (Get-Item $spawnLock).LastWriteTime).TotalHours -lt 6) {
            Log "BEAT  $runId  resume already in flight -> exit"
            exit 0
        }
        Get-Date -Format 'o' | Set-Content -Path $spawnLock

        # Record this resume in the ledger BEFORE launching: the next beat compares $newest against
        # resumed_from to decide whether this attempt actually moved the mission (above).
        if (-not $DryRun) {
            [pscustomobject]@{
                attempts     = ($attempts + 1)
                resumed_from = $newest.ToString('o')
                last_resume  = (Get-Date -Format 'o')
            } | ConvertTo-Json | Set-Content -Path $ledgerPath -Encoding UTF8
        }

        $prompt = "[heartbeat] Constitution section 11 idempotent resume beat for mission run $($cfg.run_id). " +
            "Run dir: $($cfg.run_dir). A prior orchestrator session appears dead (no activity for ${idleMin} min " +
            "- usage window, crash, or reboot). Assess state from the run dir (plan.json, journal, partial " +
            "artifacts) and recent commits on the mission branch. Idempotency rules: (1) if the mission is " +
            "complete or the run dir is gone, disarm via: powershell -NoProfile -ExecutionPolicy Bypass -File " +
            "$ScriptsDir\mission_heartbeat.ps1 disarm -RunDir '$($cfg.run_dir)' and stop. (2) if the mission is " +
            "waiting on a human gate, or a live session is actively driving this run, stop without acting. " +
            "(3) otherwise resume from committed state; from here the mission takes the queued shape " +
            "(minor questions: assume + log; blocking-critical: push notification). Never lower V-class " +
            "floors or skip mandated critics."

        try {
            if ($transcripts.Count -gt 0) {
                $sid = $transcripts[0].BaseName
                Log "BEAT  $runId  stale ${idleMin}min -> resume session $sid (cwd $($cfg.cwd))$(if ($DryRun) {' [DRY-RUN]'})"
                if (-not $DryRun) {
                    Push-Location $cfg.cwd
                    try { claude --resume $sid -p $prompt 2>&1 | ForEach-Object { Add-Content $LogFile "          $_" } }
                    finally { Pop-Location }
                }
            } else {
                # No transcript survives -- committed state in the run dir is the canonical
                # recovery point (section 11); start fresh and let it re-orient.
                Log "BEAT  $runId  stale ${idleMin}min, no transcript -> fresh resume (cwd $($cfg.cwd))$(if ($DryRun) {' [DRY-RUN]'})"
                if (-not $DryRun) {
                    Push-Location $cfg.cwd
                    try { claude -p $prompt 2>&1 | ForEach-Object { Add-Content $LogFile "          $_" } }
                    finally { Pop-Location }
                }
            }
            Log "BEAT  $runId  resume attempt finished"
        } finally {
            Remove-Item $spawnLock -ErrorAction SilentlyContinue
        }
    }

    'disarm' {
        if (-not $RunDir) { throw 'disarm requires -RunDir' }
        $runId = Split-Path -Leaf $RunDir
        $taskName = "LMO\Heartbeat-$runId"
        try { schtasks /Delete /F /TN $taskName 2>$null | Out-Null } catch { }
        Remove-Item (Join-Path $ScriptsDir "heartbeat-$runId.cmd") -ErrorAction SilentlyContinue
        Remove-Item (Join-Path $RunDir 'mission.lock') -ErrorAction SilentlyContinue
        Remove-Item (Join-Path $RunDir 'heartbeat.spawning') -ErrorAction SilentlyContinue
        Remove-Item (Join-Path $RunDir 'heartbeat.resumes.json') -ErrorAction SilentlyContinue
        Remove-Item (Join-Path $RunDir 'heartbeat.dead') -ErrorAction SilentlyContinue
        Log "DISARM $runId  task + lock + ledger removed"
    }

    'status' {
        if (-not $RunDir) { throw 'status requires -RunDir' }
        $runId = Split-Path -Leaf $RunDir
        schtasks /Query /TN "LMO\Heartbeat-$runId" /FO LIST 2>$null
        $lockPath = Join-Path $RunDir 'mission.lock'
        if (Test-Path $lockPath) { Write-Host "--- mission.lock ---"; Get-Content $lockPath }
        else { Write-Host "no mission.lock at $lockPath" }
        if (Test-Path $LogFile) { Write-Host "--- last beats ---"; Get-Content $LogFile -Tail 8 }
    }
}
